### ISSUE TITLE
Copy restriction

### ISSUE THREAD

**Issue by tower120** [nolanderc/dyn_struct#2]
Can `Copy` restriction be lifted somehow?

I want to use `dyn_struct` with `intrusive-collections` like:
```rust
#[repr(C)]
#[derive(DynStruct)]
struct SparseComponentPtrs{
    pub link: LinkedListLink,
    pub ptrs: [Option<NonNull<u8>>]
}
```

But I can't, since `LinkedListLink` does not implement `Copy`.

**Comment by nolanderc** [comment]
Ah yes, I don't see why that shouldn't be possible. I can probably have a fix up within a couple hours (my laptop is not within reach unfortunately).

If you can't wait or want to give it a stab yourself, try removing the Copy and Clone derives from `derive/src/lib.rs` and see if that works.

**Comment by tower120** [comment]
For the time being, I switched to `DynStruct`.

I'll wait for your fix up, thanks!

**Comment by nolanderc** [comment]
Version 0.3.0 now has removed the `Copy`/`Clone`restriction, please open another issue if you encounter any problems!

**Comment by nolanderc** [comment]
Nevermind, I just found an occurance of a douple-drop if you use something implementing `Drop` in the dynamic part...

**Comment by nolanderc** [comment]
Sorry about that, new version `0.3.2` should be fine :)

**Comment by tower120** [comment]
Thanks! I'll try that.
