### ISSUE TITLE
Self with #[derive(DynStruct)]

### ISSUE THREAD

**Issue by tower120** [nolanderc/dyn_struct#3]
`Self` in struct declaration with `#[derive(DynStruct)]` becomes "mangled" with some `_DynStruct_Single`:

```rust
    #[repr(C)]
    #[derive(DynStruct)]
    struct MyNode{
        pub link: ListLink<Self>,
        pub dynamic: [u32],
    }
```

Is this possible to overcome?

**Comment by nolanderc** [comment]
Hmm, in the derive macro we generate a new struct containing all but the last field (the `_DynStruct_Single` you are seeing), which we then used the `Header` in `DynStruct<Header, Tail>`. In order for this to work though, we need to guarantee that the `_DynStruct_Single` has the same layout as `MyNode` in your example. For this we use `#[repr(C)]` on both structs. However, this does mean that the `Self` gets mangled to the new struct, which as you noticed might not be all that great.

Best would be if Rust allowed us to create a tuple with `#[reprC)]` somehow, but as far as I'm aware that's not possible...

The alternative would be to change the derive macro such that all occurances of `Self` in the fields of the input be translated to `MyNode`. In general this would also need to handle cases such as `MyNode<'a, T, N>`, but should be doable. 

This is not something I'm to keen on doing though. So I suggest you either open a PR with a fix, or use the workaround of just performing the substitution manually.

**Comment by tower120** [comment]
Ok, I see, thanks!

Maybe that `Self` caveat should be mentioned in documentation...
